name: On PR
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [lts/-2, lts/-1, lts/*, current]

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm 📦️
        uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: node --version

      - run: pnpm install --frozen-lockfile

      # - run: pnpm run lint # Temporarily removed on 2024-12-09

      - run: pnpm run test

      - run: pnpm run build

      - run: pnpm run format:check

      - uses: codecov/codecov-action@v5
